/*
 * rbcParse.h --
 *
 *      TODO:Description
 *
 * Copyright (c) 2009 Samuel Green, Nicholas Hudson, Stanton Sievers, Jarrod Stormo
 * All rights reserved.
 *
 * See "license.terms" for details.
 */

#ifndef _RBCPARSE
#define _RBCPARSE

#include "tcl.h"

/*
 * A table used to classify input characters to assist in parsing
 * Tcl commands.  The table should be indexed with a signed character
 * using the CHAR_TYPE macro.  The character may have a negative
 * value.  The CHAR_TYPE macro takes a pointer to a signed character
 * and a pointer to the last character in the source string.  If the
 * src pointer is pointing at the terminating null of the string,
 * CHAR_TYPE returns TCL_COMMAND_END.
 */
#ifndef TCL_RESULT_SIZE
#define TCL_RESULT_SIZE 200
#endif

#define STATIC_STRING_SPACE 150
#define UCHAR(c) ((unsigned char)(c))
#define TCL_NORMAL 0x01
#define TCL_SPACE 0x02
#define TCL_COMMAND_END 0x04
#define TCL_QUOTE 0x08
#define TCL_OPEN_BRACKET 0x10
#define TCL_OPEN_BRACE 0x20
#define TCL_CLOSE_BRACE 0x40
#define TCL_BACKSLASH 0x80
#define TCL_DOLLAR 0x00

static unsigned char tclTypeTable[] = {
    /*
     * Negative character values, from -128 to -1:
     */

    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,

    /*
     * Positive character values, from 0-127:
     */

    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_SPACE,
    TCL_COMMAND_END,
    TCL_SPACE,
    TCL_SPACE,
    TCL_SPACE,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_SPACE,
    TCL_NORMAL,
    TCL_QUOTE,
    TCL_NORMAL,
    TCL_DOLLAR,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_COMMAND_END,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_OPEN_BRACKET,
    TCL_BACKSLASH,
    TCL_COMMAND_END,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_OPEN_BRACE,
    TCL_NORMAL,
    TCL_CLOSE_BRACE,
    TCL_NORMAL,
    TCL_NORMAL,

    /*
     * Large unsigned character values, from 128-255:
     */

    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
    TCL_NORMAL,
};

#define CHAR_TYPE(src, last) (((src) == (last)) ? TCL_COMMAND_END : (tclTypeTable + 128)[(int)*(src)])

/*
 *    The following data structure is used by various parsing
 *    procedures to hold information about where to store the
 *    results of parsing (e.g. the substituted contents of a quoted
 *    argument, or the result of a nested command).  At any given
 *    time, the space available for output is fixed, but a procedure
 *    may be called to expand the space available if the current
 *    space runs out.
 */
typedef struct ParseValueStruct ParseValue;

struct ParseValueStruct {
    char *buffer; /* Address of first character in
                   * output buffer. */
    char *next;   /* Place to store next character in
                   * output buffer. */
    char *end;    /* Address of the last usable character
                   * in the buffer. */
    void (*expandProc)(ParseValue *pvPtr, int needed);
    /* Procedure to call when space runs out;
     * it will make more space. */
    ClientData clientData; /* Arbitrary information for use of
                            * expandProc. */
};

#define TclParseBraces Rbc_ParseBraces
#define TclExpandParseValue Rbc_ExpandParseValue
#define TclParseNestedCmd Rbc_ParseNestedCmd
#define TclParseQuotes Rbc_ParseQuotes

void Rbc_ExpandParseValue(ParseValue *parsePtr, int needed);
int Rbc_ParseNestedCmd(Tcl_Interp *interp, char *string, int flags, char **termPtr, ParseValue *parsePtr);
int Rbc_ParseBraces(Tcl_Interp *interp, char *string, char **termPtr, ParseValue *parsePtr);
int Rbc_ParseQuotes(Tcl_Interp *interp, char *string, int termChar, int flags, char **termPtr, ParseValue *parsePtr);

#endif /* _RBCPARSE */
